# Site
name: 'Foods for Brain'
description: 'Foods for Brain is a personal blog on Food, Science and lessons in our everyday life.'
logo: 'assets/images/logo2.png'
favicon: 'assets/images/logo2.png'
url: 'https://foodsforbrain.com'
disqus: 'demowebsite'
email: 'yamamoto.mai88@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    mai:
      name:           "Mai Yamamoto"
      site:           https://www.linkedin.com/in/yamamotomai88/
      avatar:         assets/images/avatar1.jpg
      bio:            "Product manager in health tech with Ph.D. in Chemical Biology.  
      		       I am passionate about building strong product teams and constantly learning something new along the way!"
      email:          yamamoto.mai88@gmail.com
      twitter:        https://twitter.com/Maiski8_8
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: mai
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
